# Ghidra script generated by bx — run on the same binary.
# Recreates bx marks/bookmarks as labels + EOL comments at their addresses.
# @category bx
items = [
    (0x0, "elf_str", "bx str: '.ELF...'"),
    (0x0, "bx_bookmark_e", "bx bookmark 'e'"),
    (0x0, "bx_bookmark_m", "bx bookmark 'm'"),
]
for addr, name, comment in items:
    a = toAddr(addr)
    try:
        createLabel(a, name, False)
    except Exception as e:
        print("bx: label %s @ %s failed: %s" % (name, a, e))
    if comment:
        setEOLComment(a, comment)
print("bx: applied %d item(s)" % len(items))
