//! Hand-off bridges: export bxx's marks and bookmarks as a Ghidra (Jython) or
//! radare2 script that recreates them as labels + comments at the right
//! addresses. The literal "annotate in bxx → push to Ghidra" workflow.
//!
//! bxx works in file offsets; Ghidra/r2 work in virtual addresses. When the
//! binary is an ELF we translate offsets via the LOAD segments (see
//! [`crate::analysis::triage::Report::off_to_vaddr`]); otherwise we pass the
//! offset through (correct for raw/flat images loaded at 0).

use std::collections::BTreeMap;
use std::path::Path;

use crate::analysis::triage::Report;
use crate::annotations::Region;
use crate::buffer::FileBuffer;

/// One item to recreate downstream: address, sanitized label, comment.
struct Item {
    addr: u64,
    name: String,
    comment: String,
}

fn sanitize(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

/// Reduce a comment to a safe ASCII whitelist so a crafted file's bytes can't
/// inject into the generated Ghidra/r2 script. Drops quotes, backslashes,
/// newlines, and r2/shell metacharacters (`; @ # $ & | !` quotes, etc.);
/// collapses runs of removed/space chars.
fn safe_text(s: &str) -> String {
    let mapped: String = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || " .,:_=+-*/()[]<>".contains(c) {
                c
            } else {
                ' '
            }
        })
        .collect();
    mapped.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Build the item list (offsets translated to addresses where possible).
fn collect(
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> (Vec<Item>, usize) {
    let to_addr = |off: u64| -> Option<u64> {
        match triage {
            Some(t) => t.off_to_vaddr(off),
            None => Some(off),
        }
    };
    let mut items = Vec::new();
    let mut skipped = 0;
    for r in regions {
        match to_addr(r.start) {
            Some(addr) => {
                let val = r.decode(buf);
                let detail = match &r.note {
                    Some(n) => format!("{val}  {n}"),
                    None => val,
                };
                items.push(Item {
                    addr,
                    name: sanitize(&r.label),
                    comment: safe_text(&format!("bxx {}: {detail}", r.rtype)),
                });
            }
            None => skipped += 1,
        }
    }
    for (k, off) in bookmarks {
        match to_addr(*off) {
            Some(addr) => items.push(Item {
                addr,
                name: format!("bxx_bookmark_{}", sanitize(&k.to_string())),
                comment: safe_text(&format!("bxx bookmark {k}")),
            }),
            None => skipped += 1,
        }
    }
    (items, skipped)
}

/// Ghidra Python (Jython) script. Run from the Script Manager on the same
/// binary, or `analyzeHeadless … -postScript <file>`.
pub fn write_ghidra(
    out: &Path,
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> Result<(usize, usize), String> {
    let (items, skipped) = collect(buf, regions, bookmarks, triage);
    let mut body = String::new();
    for it in &items {
        let c = it.comment.replace('"', "'");
        body.push_str(&format!("    (0x{:X}, \"{}\", \"{}\"),\n", it.addr, it.name, c));
    }
    let script = format!(
        "# Ghidra script generated by bxx — run on the same binary.\n\
         # Recreates bxx marks/bookmarks as labels + EOL comments at their addresses.\n\
         # @category bxx\n\
         items = [\n{body}]\n\
         for addr, name, comment in items:\n\
         \x20   a = toAddr(addr)\n\
         \x20   try:\n\
         \x20       createLabel(a, name, False)\n\
         \x20   except Exception as e:\n\
         \x20       print(\"bxx: label %s @ %s failed: %s\" % (name, a, e))\n\
         \x20   if comment:\n\
         \x20       setEOLComment(a, comment)\n\
         print(\"bxx: applied %d item(s)\" % len(items))\n"
    );
    std::fs::write(out, script).map_err(|e| format!("{}: {e}", out.display()))?;
    Ok((items.len(), skipped))
}

/// radare2 script. Load with `r2 -i <file> <binary>` or `. <file>` inside r2.
pub fn write_r2(
    out: &Path,
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> Result<(usize, usize), String> {
    let (items, skipped) = collect(buf, regions, bookmarks, triage);
    let mut s = String::from("# radare2 script generated by bxx\n");
    for it in &items {
        s.push_str(&format!("f bxx.{} @ 0x{:X}\n", it.name, it.addr));
        s.push_str(&format!("CCu {} @ 0x{:X}\n", it.comment, it.addr));
    }
    std::fs::write(out, s).map_err(|e| format!("{}: {e}", out.display()))?;
    Ok((items.len(), skipped))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn safe_text_strips_injection() {
        // r2 / shell / quote metacharacters are dropped
        assert_eq!(safe_text("a; rm -rf / @ evil"), "a rm -rf / evil");
        for nasty in ["\";ls", "a | b", "x && y", "back\\slash", "new\nline", "a$(id)", "a#c"] {
            let s = safe_text(nasty);
            for bad in ['"', '\'', '\\', ';', '@', '#', '$', '&', '|', '!', '\n', '\r'] {
                assert!(!s.contains(bad), "{nasty:?} -> {s:?} still has {bad:?}");
            }
        }
    }

    #[test]
    fn sanitize_label_is_identifier_safe() {
        for nasty in ["a.b[0]", "ev;il", "0start", "", "a b c", "x\"y"] {
            let s = sanitize(nasty);
            assert!(
                s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                "{nasty:?} -> {s:?}"
            );
            assert!(!s.starts_with(|c: char| c.is_ascii_digit()));
        }
    }
}
