//! Hand-off bridges: export bx's marks and bookmarks as a Ghidra (Jython) or
//! radare2 script that recreates them as labels + comments at the right
//! addresses. The literal "annotate in bx → push to Ghidra" workflow.
//!
//! bx works in file offsets; Ghidra/r2 work in virtual addresses. When the
//! binary is an ELF we translate offsets via the LOAD segments (see
//! [`crate::analysis::triage::Report::off_to_vaddr`]); otherwise we pass the
//! offset through (correct for raw/flat images loaded at 0).

use std::collections::BTreeMap;
use std::path::Path;

use crate::analysis::triage::Report;
use crate::annotations::Region;
use crate::buffer::FileBuffer;

/// One item to recreate downstream: address, sanitized label, comment.
struct Item {
    addr: u64,
    name: String,
    comment: String,
}

fn sanitize(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

fn one_line(s: &str) -> String {
    s.replace(['\n', '\r'], " ")
}

/// Build the item list (offsets translated to addresses where possible).
fn collect(
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> (Vec<Item>, usize) {
    let to_addr = |off: u64| -> Option<u64> {
        match triage {
            Some(t) => t.off_to_vaddr(off),
            None => Some(off),
        }
    };
    let mut items = Vec::new();
    let mut skipped = 0;
    for r in regions {
        match to_addr(r.start) {
            Some(addr) => {
                let val = r.decode(buf);
                let detail = match &r.note {
                    Some(n) => format!("{val}  {n}"),
                    None => val,
                };
                items.push(Item {
                    addr,
                    name: sanitize(&r.label),
                    comment: one_line(&format!("bx {}: {detail}", r.rtype)),
                });
            }
            None => skipped += 1,
        }
    }
    for (k, off) in bookmarks {
        match to_addr(*off) {
            Some(addr) => items.push(Item {
                addr,
                name: format!("bx_bookmark_{k}"),
                comment: format!("bx bookmark '{k}'"),
            }),
            None => skipped += 1,
        }
    }
    (items, skipped)
}

/// Ghidra Python (Jython) script. Run from the Script Manager on the same
/// binary, or `analyzeHeadless … -postScript <file>`.
pub fn write_ghidra(
    out: &Path,
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> Result<(usize, usize), String> {
    let (items, skipped) = collect(buf, regions, bookmarks, triage);
    let mut body = String::new();
    for it in &items {
        let c = it.comment.replace('"', "'");
        body.push_str(&format!("    (0x{:X}, \"{}\", \"{}\"),\n", it.addr, it.name, c));
    }
    let script = format!(
        "# Ghidra script generated by bx — run on the same binary.\n\
         # Recreates bx marks/bookmarks as labels + EOL comments at their addresses.\n\
         # @category bx\n\
         items = [\n{body}]\n\
         for addr, name, comment in items:\n\
         \x20   a = toAddr(addr)\n\
         \x20   try:\n\
         \x20       createLabel(a, name, False)\n\
         \x20   except Exception as e:\n\
         \x20       print(\"bx: label %s @ %s failed: %s\" % (name, a, e))\n\
         \x20   if comment:\n\
         \x20       setEOLComment(a, comment)\n\
         print(\"bx: applied %d item(s)\" % len(items))\n"
    );
    std::fs::write(out, script).map_err(|e| format!("{}: {e}", out.display()))?;
    Ok((items.len(), skipped))
}

/// radare2 script. Load with `r2 -i <file> <binary>` or `. <file>` inside r2.
pub fn write_r2(
    out: &Path,
    buf: &FileBuffer,
    regions: &[Region],
    bookmarks: &BTreeMap<char, u64>,
    triage: Option<&Report>,
) -> Result<(usize, usize), String> {
    let (items, skipped) = collect(buf, regions, bookmarks, triage);
    let mut s = String::from("# radare2 script generated by bx\n");
    for it in &items {
        s.push_str(&format!("f bx.{} @ 0x{:X}\n", it.name, it.addr));
        s.push_str(&format!("CCu {} @ 0x{:X}\n", it.comment, it.addr));
    }
    std::fs::write(out, s).map_err(|e| format!("{}: {e}", out.display()))?;
    Ok((items.len(), skipped))
}
